# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34cbbdd44e195047f533365aa2e551bffbc5a4c0c01dc3e8d2d1949d25e2229f3df32e248ec700549875987820c7602960a8eb6b6b9df183604d9140008d68b1

test:
  secret_key_base: ef385bee5648a66a7eee7c2c835494eb6c859357e27f945a753e6eb39632c5c9162ea6eba1f8a5eab34c9684d5a0bd6b6d2d4f77d88b2a524dc151646139c41d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
